### PR TITLE
Feature/make gfxcardstatus great again

### PR DESCRIPTION
**Pull request by clementpadovani**

### CODE REVIEW

**Comment by codykrieger** [comment]
Thanks for this! I've not fully reviewed this yet, but what I've seen so far looks good. I haven't forgotten about reviewing the rest—just incredibly swamped right now.

**Comment by lukaszraczylo** [comment]
Any update on this?

**Comment by realies** [comment]
Bump.

**Comment by mijndert** [comment]
Would love to have all of this merged!

**Comment by rdemendoza** [comment]
Bump.

**Comment by Crocmagnon** [comment]
@codykrieger ? :)

**Comment by voltechs** [comment]
@codykrieger have you considered opening the doors to accepting another core contributor? This is a very nice little utility that would be wonderful to keep up-to-date. Don't try to take on the world yourself, let the OSS community help you! :)

(Said another way: any update on this?)

**Comment by codykrieger** [comment]
Sorry all—no updates to give at the moment. Far too busy with other things to focus on this at the moment.

@voltechs To answer your question, yeah, I'd be willing to consider it. It'd just have to be the right person.

**Comment by hughperkins** [comment]
To be fair, nothing stops anyone from using @clementpadovani 's fork. @clementpadovani , do you know how to fix https://github.com/codykrieger/gfxCardStatus/issues/312 ? If you fix that, I for one will use your fork :)  (well, I'd prefer to have at least one person peer-review your changes on the whole, not necessarily Cody, just to ... [after going off to actually look at the diffs] omg, thats a whole bunch of changes :P

@clementpadovani I reckon if I was @codykrieger , I'd probably ask you to break your changes down into a series of bite-sized changes, ideally without huge chunks of too-large-to-render-in-github diffs etc. This will make it much more manageable, and reduce cognitive load on the reviewer :)

**Comment by realies** [comment]
image

**Comment by hughperkins** [comment]
I've started using gswitch, by Cody schrank. Working ok for me so far...

**Comment by realies** [comment]
Thanks for the tip!

**Comment by Crocmagnon** [comment]
gSwitch doesn't allow me to force integrated only on a MacBook Pro 15" 2017, so to me it works the same as gfxCardStatus.

**Comment by rnsc** [comment]
Is this still going to happen sometime in the future?

**Comment by johnalanwoods** [comment]
@hughperkins great shout for gswitch, I'm using that too since gfx is broken in Catalina.

**Pull request closed without merging**
