### PR TITLE
Possible fix #242

### LINKED ISSUE #242: Switching to Integrated Only switches to Discrete Only
Switching to Integrated Only switches the setting to Discrete Only but continues to run on the integrated GPU.

### PR DESCRIPTION
**Pull request by fishcharlie**
This looks to solve issue #242. Not sure if breaks other code or a solid long term solution but this solution worked for me personally.

### CODE REVIEW

**Comment by codykrieger** [comment]
Unfortunately this isn't a proper fix. Merely checking to see if the integrated GPU is active could mean you're on Dynamic Switching as well—Integrated Only means you're more or less locked to the integrated GPU.

Thanks, though!

**Comment by fishcharlie** [comment]
Maybe I'm going crazy but that's what the dynamic bool is checking for. If dynamic is true it sets on state to dynamicSwitching. If dynamic is false then it checks to see if it's using the integrated or dedicated by calling [GSMux isUsingIntegratedGPU].

So it should still be checking dynamic vs integrated correct?

**Comment by fishcharlie** [comment]
@codykrieger Am I wrong with that or? :)

**Comment by codykrieger** [comment]
Yeah. Integrated Only means more than just “is Dynamic Switching off && is the integrated GPU active.” This change doesn't preserve the meaning of Integrated Only.

#242 might be the latest incarnation of #103; perhaps it's just worse on macOS Sierra than it was before.

**Pull request closed without merging**
